on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          lutter-version: '3.7.12'
          channel: 'stable'
          cache: true
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --debug --split-per-abi
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: v1.0.${{ github.run_number }}-3
          token: ${{ secrets.STOCK_APP_TOKEN }}


# GITHUB ACTIONS CI/CD CODE
